SELECT ED3.ID AS ID
FROM ECOLI_DATA ED1 INNER JOIN ECOLI_DATA ED2 ON ED1.ID = ED2.PARENT_ID
                    INNER JOIN ECOLI_DATA ED3 ON ED2.ID = ED3.PARENT_ID
                   WHERE ED1.PARENT_ID IS NULL
                    GROUP BY ED3.ID
                    ORDER BY ED3.ID ASC;