
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - CP.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON C.CAR_ID = CH.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP ON C.CAR_TYPE = CP.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                      WHERE START_DATE < '2022-12-01' AND
                            END_DATE > '2022-11-01'
                      )
                      AND CP.DURATION_TYPE = '30일 이상'
             GROUP BY C.CAR_ID
             HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE < 2000000)
             ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
             
