SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
       COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT U.USER_ID) /(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PURCHASED_RATIO
FROM USER_INFO U 
JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '2021%' -- 2021년 가입
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH