SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR
  ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) T
    )
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;